name: Publish Pre Release

on:
  push:
    branches:
      - development

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      build_number: ${{ steps.extract.outputs.build_number }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install conventional-changelog-conventionalcommits

      - name: Create changelog
        id: changelog
        uses: DevScyu/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.PRIVATE_TOKEN }}
          preset: conventionalcommits
          release-count: 1
          pre-commit: ./.github/.pre-commit.js
          config-file-path: ./.github/.config.js
          create-summary: true
          version-file: ./version.json
          skip-git-pull: true
          pre-release: true
          pre-release-identifier: beta

      - name: Extract build information
        id: extract
        run: "echo ::set-output name=build_number::`echo ${{ steps.changelog.outputs.tag }} | cut -d'.' -f4`"

      - name: Upload version information
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.gradle

  build:
    name: Build
    needs: [changelog] # Build needs the new version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3 # Download version information from changelog
        with:
          name: build

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
          cache: "gradle"

      - name: Build
        env:
          BUILD_NUMBER: ${{ needs.changelog.outputs.build_number }}
        run: ./gradlew build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs

  artifact:
    name: Rename Artifact
    needs: [build, changelog]
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/libs

      - name: Rename artifact
        run: mv build/libs/wynntils-*.jar build/Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}.jar

      - name: Upload renamed artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}.jar

  release-to-gh:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: [changelog, artifact]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}.jar
          tag_name: ${{ needs.changelog.outputs.tag }}
          prerelease: true
          body: ${{ needs.changelog.outputs.clean_changelog }}
          target_commitish: ${{ github.sha }}

  release-to-cf:
    name: Release to CurseForge
    runs-on: ubuntu-latest
    needs: [changelog, artifact]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}.jar
          game_endpoint: minecraft
          # Minecraft 1.12.2: 6756
          # Forge: 7498
          # Java 8: 4458
          game_versions: "6756,7498,4458"
          project_id: 303451
          token: ${{ secrets.CF_API_TOKEN }}
          release_type: beta
          display_name: Wynntils ${{ needs.changelog.outputs.tag }}
          changelog_type: markdown
          changelog: "${{ needs.changelog.outputs.changelog }}"

  release-to-modrinth:
    name: Release to Modrinth
    runs-on: ubuntu-latest
    needs: [changelog, artifact]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build

      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1.0.0
        with:
          token: ${{ secrets.MODRINTH_API_TOKEN }}
          file_path: Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}.jar
          name: Wynntils ${{ needs.changelog.outputs.tag }}
          version: ${{ needs.changelog.outputs.tag }}
          changelog: "${{ needs.changelog.outputs.changelog }}"
          game_versions: 1.12.2
          release_type: beta
          loaders: forge
          featured: true
          project_id: dU5Gb9Ab
