name: Publish Release

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install conventional-changelog-conventionalcommits

      - name: Create changelog
        id: changelog
        uses: DevScyu/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.PRIVATE_TOKEN }}
          git-user-name: 'Wynntils'
          git-user-email: 'admin@wynntils.com'
          pre-commit: ./.github/.pre-commit.js
          config-file-path: ./.github/.config.js
          skip-version-file: true
          skip-git-pull: true

      - name: Upload version information
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.gradle

  build:
    name: Build
    needs: [changelog] # Build needs the new version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3 # Download version information from changelog
        with:
          name: build

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
          cache: "gradle"

      - name: Build
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs

  artifact:
    name: Rename Artifact
    needs: [build, changelog]
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/libs

      - name: Rename artifact
        run: mv build/libs/wynntils-*.jar build/Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}.jar

      - name: Upload renamed artifact
        uses: actions/upload-artifact@v3
        with:
          name: Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}
          path: build/Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}.jar


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [artifact, changelog]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build

      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: dU5Gb9Ab
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          curseforge-id: 303451
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          github-tag: ${{ needs.changelog.outputs.tag }}
          github-token: ${{ secrets.PRIVATE_TOKEN }}

          files-primary: Wynntils-MC1.12.2-${{ needs.changelog.outputs.tag }}.jar
          files-secondary: ""

          name: Wynntils ${{ needs.changelog.outputs.tag }}
          version: ${{ needs.changelog.outputs.tag }}
          version-type: release
          changelog: ${{ needs.changelog.outputs.changelog }}

          loaders: forge
          game-versions: 1.12.2
          java: 8
